In [1]:
import os
os.environ["KERAS_BACKEND"] = "torch"
import keras
import keras.ops as K
from keras.layers import Input, Flatten, Dense
from keras.optimizers import Adam
from keras.metrics import BinaryAccuracy

# from keras.models import Sequential
from deel.lip.model import Sequential

from deel.lip.layers import (
    SpectralDense,
    SpectralConv2D,
    ScaledL2NormPooling2D,
    FrobeniusDense,
)
from deel.lip.activations import GroupSort, GroupSort2
from deel.lip.losses import HKR, KR, HingeMargin, MulticlassHKR, MulticlassKR

import numpy as np
import decomon
import sys
sys.path.append('..')
from data_processing import load_data, select_data_for_radius_evaluation_MNIST08
from radius_evaluation_tools import compute_binary_certificate, starting_point_dichotomy

import matplotlib.pyplot as plt

# Loading data

In [2]:
x_train, x_test, y_train, y_test, y_test_ord = load_data("MNIST08")

In [28]:
x_test[0].flatten()

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [3]:
model_path = "/home/aws_install/robustess_project/lip_models/demo3_FC_vanilla_MNIST08_channelfirst_False_disj_Neurons_single_output.keras"
model = keras.models.load_model(model_path)
model.compile(
   
    loss=HKR(
        alpha=10.0, min_margin=1.0
    ),  # HKR stands for the hinge regularized KR loss
    metrics=[
        # KR,  # shows the KR term of the loss
        HingeMargin(min_margin=1.0),  # shows the hinge term of the loss
    ],
    optimizer=Adam(learning_rate=0.001),)

/home/aws_install/miniconda3/envs/k3torchenv/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 12 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [4]:
model_bis = keras.models.load_model("/home/aws_install/robustess_project/lip_models/demo3_FC_vanilla_MNIST08_channelfirst_False_disj_Neurons_single_output_converted_4logits.keras")
model_bis.compile(
        # decreasing alpha and increasing min_margin improve robustness (at the cost of accuracy)
        # note also in the case of lipschitz networks, more robustness require more parameters.
        loss=MulticlassHKR(alpha=100, min_margin=0.25),
        optimizer=Adam(1e-4),
        metrics=["accuracy", MulticlassKR()],)

/home/aws_install/miniconda3/envs/k3torchenv/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 14 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [5]:
images, labels, idx_list = select_data_for_radius_evaluation_MNIST08(x_test, y_test_ord, model_bis)

# Selecting/Generating Samples

2.5725006639080936

In [6]:
from lipschitz_decomon_tools import get_local_maximum, echantillonner_boule_l2_simple, square_backward_bounds, function_to_optimize_all


In [7]:
pt_choosen = 0
x = x_train[pt_choosen:pt_choosen+1].flatten()
label = y_test_ord[pt_choosen:pt_choosen+1]
eps=0.1
nb_pts = 100

In [8]:
label

array([1.], dtype=float32)

We generate nb_pts random points within the ball.

In [21]:
y_list = []
for i in range(nb_pts):
    ech = echantillonner_boule_l2_simple(x, eps)
    print(np.linalg.norm(x-ech))
    y_list.append(ech)

0.015201974378848987
0.06491554270197768
0.003621379431239845
0.06754907538578593
0.09903521469160584
0.029797984427808163
0.09186743674104392
0.04791295453456317
0.05511254077005156
0.009393691227681387
0.018536644954678026
0.09000484520966723
0.03350145109018664
0.049916169552937074
0.05345554898948477
0.02244980514267857
0.060514329198850116
0.05560933809356284
0.030956561050150908
0.029719879972490214
0.06936226548200737
0.05744362930686122
0.011545103150989184
0.04136165304200139
0.05536316355360669
0.053555898440521194
0.042026583273745234
0.09036882882622736
0.03658443931022101
0.04952806308931565
0.07382004386469289
0.05019249622273678
0.05283944331399194
0.05020234165764822
0.09012559436703346
0.0101254397832229
0.08650774825453744
0.06977540787563341
0.024269983366415924
0.0010959886828862987
0.045908509140125064
0.03286312497538666
0.019639904938023898
0.08347095718318144
0.05650530536220198
0.09459684789411603
0.09946521922156554
0.09115042039879273
0.09202617932369629
0.05

# Solving

We solve our problem with these 10 random points

In [24]:
eps, x, model

(0.1,
 array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        

In [11]:
x_adv, f_adv = get_local_maximum(x, label, eps, y_list, model)

empirical max values [1.1041306770486101, 1.1041526648709148, 1.1041748278217276]
empirical min values [1.1037186501977927, 1.1037731108776385, 1.1037855004833386]


In [12]:
f_adv

1.1024412371283288

In [13]:
# from radius_evaluation_tools import single_compute_relaxation_radius

In [14]:
# eps_working = single_compute_relaxation_radius(pt_choosen, images, labels, model, nb_pts)

In [15]:
# eps_working

In [16]:
# y_list = [x]
# f_list = [get_local_maximum(x, label, eps, y_list, model)[1]]
# for i in range(10):
#     print(i)
#     i = 2*i
#     nb_pts = i+1
#     y_list.append(echantillonner_boule_l2_simple(x, eps))
#     x_adv, f_adv = get_local_maximum(x, label, eps, y_list, model)
#     f_list.append(f_adv)

# list_i = []
# for i in range(3):
#     list_i.append(2*i)


# plt.scatter(list_i, f_list)
# plt.xlabel("nb yi")
# plt.ylabel("max function")
# plt.show()

In [17]:
x_ech = echantillonner_boule_l2_simple(x, eps)
print(np.linalg.norm(x-x_ech))
x_ball_center = np.asarray(x, dtype=np.float64)

l = x-eps
u = x+eps

W_list = []
b_list = []
for y_i in y_list:
    # W, b = square_backward_bounds(l,u,y_i)
    W, b = square_backward_bounds(l,u,y_i)
    print(b)
    W_list.append(W)
    b_list.append(b)
    
function_to_optimize_all(x_ech, label, W_list, b_list, y_list, model)

0.019025679456054868
[7.84604102]
[7.77958662]
[7.83261412]
[7.829268]
[7.83920743]
[7.87042073]
[7.84141434]
[7.8207467]
[7.8369773]
[7.83904039]
[7.83446119]
[7.85022571]
[7.77809069]
[7.83815946]
[7.84377785]
[7.81942454]
[7.84121799]
[7.86456624]
[7.87555495]
[7.87950899]
[7.74783914]
[7.87382576]
[7.8564392]
[7.84147046]
[7.83336983]
[7.83937924]
[7.82831407]
[7.85280471]
[7.83915003]
[7.89716926]
[7.83434915]
[7.87720727]
[7.79875771]
[7.78025858]
[7.89924398]
[7.83335646]
[7.84230909]
[7.88622608]
[7.81454224]
[7.88168138]
[7.83090824]
[7.76686332]
[7.81492004]
[7.83490683]
[7.86382729]
[7.92871234]
[7.90380516]
[7.74910088]
[7.85356079]
[7.8416835]
[7.81775084]
[7.87608943]
[7.86496641]
[7.81722592]
[7.84023447]
[7.83483133]
[7.83479732]
[7.79052772]
[7.82145016]
[7.8274251]
[7.8388823]
[7.83219243]
[7.84566404]
[7.84333925]
[7.85126678]
[7.85264175]
[7.91328584]
[7.79860201]
[7.86507474]
[7.77609332]
[7.84541764]
[7.87521637]
[7.83977129]
[7.84070653]
[7.80174707]
[7.8098242]


1.103922819272476

## Pyiavski

In [18]:
y_list = []
y_list.append(x)

for i in range(20):
    x_adv, f_adv = get_local_maximum(x, label, eps, y_list, model)
    y_list.append(x_adv)

empirical max values [1.0999281, 1.0999281, 1.0999281]
empirical min values [1.0999281, 1.0999281, 1.0999281]
empirical max values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical min values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical max values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical min values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical max values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical min values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical max values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical min values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical max values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]
empirical min values [1.0999281406402588, 1.0999281406402588, 1.0999281406402588]


KeyboardInterrupt: 

In [ ]:
f_adv

23.89740562438965

In [ ]:
np.sum(W_list[5] - W_list[1] != 0)

784

# Tests

In [ ]:
import pdb

In [ ]:
def square_backward_bounds_reduced(l, u, y):
    # l (4,)
    # u (4,)
    # y (4,)
    l = l[151:153]
    u = u[151:153]
    y = y[151:153]
    print(l, u, y)
    u = u - y
    l = l - y
    print(u, l)

    W = u + l #(4,)
    print(W)
    b = np.sum(-u*l) - W@y #scalar
    # pdb.set_trace()
    return W, np.array(b)[None]#(4,) & (1,)

In [ ]:
v = x-eps
idx = np.nonzero(x)

In [ ]:
idx

(array([145, 146, 147, 148, 173, 174, 175, 176, 177, 182, 183, 184, 185,
        186, 202, 203, 204, 205, 206, 210, 211, 212, 213, 214, 215, 216,
        217, 230, 231, 232, 233, 234, 238, 239, 240, 241, 242, 243, 244,
        245, 246, 260, 261, 262, 263, 264, 268, 269, 270, 271, 272, 273,
        274, 289, 290, 291, 292, 293, 299, 300, 301, 302, 318, 319, 320,
        321, 322, 326, 327, 328, 329, 330, 346, 347, 348, 349, 350, 353,
        354, 355, 356, 357, 375, 376, 377, 378, 379, 380, 381, 382, 383,
        384, 385, 404, 405, 406, 407, 408, 409, 410, 411, 412, 432, 433,
        434, 435, 436, 437, 438, 458, 459, 460, 461, 462, 463, 464, 465,
        466, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 513, 514,
        515, 516, 517, 519, 520, 521, 522, 541, 542, 543, 544, 545, 548,
        549, 550, 569, 570, 571, 572, 576, 577, 578, 579, 597, 598, 599,
        600, 604, 605, 606, 607, 625, 626, 627, 628, 629, 630, 631, 632,
        633, 634, 635, 654, 655, 656, 657, 658, 659

In [ ]:
y_list[5][145: 147]

array([0.63515117, 0.98249315])

In [ ]:
x[145: 147]

array([0.63529414, 0.99215686], dtype=float32)

In [ ]:
W1, b1 = square_backward_bounds_reduced(x-eps, x+eps, y_list[2])

[-0.5 -0.5] [0.5 0.5] [0.00628395 0.00533263]
[0.49371605 0.49466737] [-0.50628395 -0.50533263]
[-0.0125679  -0.01066527]


In [ ]:
W3, b3 = square_backward_bounds_reduced(np.asarray(x, dtype=np.float32)-eps, np.asarray(x, dtype=np.float32)+eps, y_list[2])

[-0.5 -0.5] [0.5 0.5] [0.00628395 0.00533263]
[0.49371605 0.49466737] [-0.50628395 -0.50533263]
[-0.0125679  -0.01066527]


In [ ]:
W2, b2 = square_backward_bounds_reduced(np.asarray(x, dtype=np.float64)-eps, np.asarray(x, dtype=np.float64)+eps, y_list[5])

[-0.5 -0.5] [0.5 0.5] [-0.00148758 -0.01061017]
[0.50148758 0.51061017] [-0.49851242 -0.48938983]
[0.00297516 0.02122035]


In [ ]:
W1

array([ 0.01725835, -0.00543194])

In [ ]:
W1

array([ 0.01725835, -0.00543194])

In [ ]:
x_ech = echantillonner_boule_l2_simple(x, eps)

In [ ]:
function_to_optimize_all(x_ech, label, [W1, W2], [b1, b2], y_list[151:153], model)

UnboundLocalError: local variable 'function' referenced before assignment

In [ ]:
outputs = []
for i in range(len(y_list)):
    output = model(y_list[i].reshape((1,28,28))[None]).cpu().detach().numpy()[0,0] +\
                1*np.sqrt(W_list[i]@x+b_list[i]) #scalar
    outputs.append(output)
function = np.min(outputs)

In [ ]:
function

10.681383384238005

## Test comparison function without relaxation vs lip certificate

In [ ]:
def f_bar(z, y_list):
    outputs = []
    for i in range(len(y_list)):
        output = model(y_list[i].reshape((1,28,28))[None]).cpu().detach().numpy()[0,0] +\
                    1*np.sqrt(np.sum(np.square(z - y_list[i]))) #scalar
        outputs.append(output)
    function = np.min(outputs)
    return function

In [ ]:
nb_pts = 200
pt_choosen = 3
x = images[pt_choosen:pt_choosen+1].flatten().detach().cpu().numpy()
label = labels[pt_choosen:pt_choosen+1]
result = []
# eps = np.abs(model(images[pt_choosen:pt_choosen+1]).detach().cpu().numpy())*1.01
# eps_list = np.linspace(1.66, 1.81, 10)
# eps_list = np.linspace(3.03, 3.25, 10)
# eps_list = np.linspace(3.05, 3.35, 10)
# eps_list = np.linspace(4.69, 4.74, 10)
eps_list = [4.75]
for eps in eps_list:
    print(eps)
    y_list = []
    for i in range(nb_pts):
        ech = echantillonner_boule_l2_simple(x, eps, uniform=False)
        # print(np.linalg.norm(x-ech))
        y_list.append(ech)

    result.append(np.max([f_bar(echantillonner_boule_l2_simple(x, eps, uniform=False), y_list) for _ in range(100)]))

4.75


In [ ]:
model(images[pt_choosen:pt_choosen+1])

tensor([[-4.6951]], device='cuda:0', grad_fn=<MmBackward0>)

In [ ]:
result

[0.023737574173073206]

In [ ]:
result

[-0.110719492398057,
 -0.08017869301770464,
 -0.04154762901225162,
 -0.04609906470403491,
 -0.011316823696587264,
 -0.055861984398299036,
 -0.055628969752287816,
 0.019360363070336284,
 -0.02671810987077805,
 -0.06817730949112466]

In [ ]:
eps_list

array([1.66      , 1.67666667, 1.69333333, 1.71      , 1.72666667,
       1.74333333, 1.76      , 1.77666667, 1.79333333, 1.81      ])

pour nb point donné quel est le rayon empirique obtenu : faire meme tableau que slides